//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gasolineras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasolinera
    {
        public int Id { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Marca { get; set; }
        public string Amenidades { get; set; }
        public Nullable<double> PrecioMagna { get; set; }
        public Nullable<double> PrecioPremium { get; set; }
        public Nullable<double> PrecioDiesel { get; set; }
        public string HoraApertura { get; set; }
        public string HoraCierre { get; set; }
    
        public virtual Marca Marca1 { get; set; }
    }
}
