//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gasolineras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasolinera
    {
        public int Id { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Marca { get; set; }
        public string Amenidades { get; set; }
        public Nullable<double> PrecioMagna { get; set; }
        public Nullable<double> PrecioPremium { get; set; }
        public Nullable<double> PrecioDiesel { get; set; }
        public string HoraApertura { get; set; }
        public string HoraCierre { get; set; }
    
        public virtual Marca Marca1 { get; set; }
    }
}
