//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gasolineras.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GasolinerasEntities1 : DbContext
    {
        public GasolinerasEntities1()
            : base("name=GasolinerasEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amenidade> Amenidades { get; set; }
        public virtual DbSet<Gasolinera> Gasolineras { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
    }
}
